package errors

import "errors"

var (
	ERR_EMAIL_IS_EMPTY            = errors.New("Email is empty")
	ERR_LOGIN                     = errors.New("Failed to signing")
	ERR_REGISTER                  = errors.New("Failed to register")
	ERR_UPDATE_USER               = errors.New("Failed to update user")
	ERR_UPDATE_ROLE               = errors.New("Failed to update role")
	ERR_DELETE_USER               = errors.New("Failed to delete user")
	ERR_DELETE_MEMBERSHIP_PLAN    = errors.New("Failed to delete membership plan")
	ERR_DELETE_ROLE               = errors.New("Failed to delete role")
	ERR_CREATE_ROLE               = errors.New("Failed to create new Role")
	ERR_CREATE_MEMBERSHIP_PLAN    = errors.New("Failed to create new Membership Plan")
	ERR_CREATE_PURCHASE           = errors.New("Purchase Failed")
	ERR_PASSWORD_IS_EMPTY         = errors.New("Password is empty")
	ERR_PHONE_NUMBER_IS_EMPTY     = errors.New("Phone number is empty")
	ERR_ROLE_IS_EMPTY             = errors.New("Role is empty")
	ERR_BCRYPT_PASSWORD           = errors.New("Failed to bcrypt password")
	ERR_TOKEN                     = errors.New("Failed to create new token")
	ERR_GET_DATA                  = errors.New("Failed to get data from database")
	ERR_NOT_FOUND                 = errors.New("Data not Found")
	ERR_EMAIL_NOT_FOUND           = errors.New("Email not found")
	ERR_WRONG_PASSWORD            = errors.New("Wrong password")
	ERR_MEMBERSHIP_NAME_EMPTY     = errors.New("Membership plan is empty")
	ERR_MEMBERSHIP_DURATION_EMPTY = errors.New("Membership duration is empty")
	ERR_MEMBERSHIP_PRICE_EMPTY    = errors.New("Membership price is empty")
	ERR_UNAUTHORIZE               = errors.New("Unauthorize user")
)
